version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paysplis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1omo0gj78es2y"
s3_prefix = "paysplis"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

